# Generated by Django 5.0.1 on 2024-01-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AircraftID", models.CharField(max_length=255, null=True)),
                ("EquipmentType", models.CharField(max_length=255, null=True)),
                ("TypeCode", models.CharField(max_length=255, null=True)),
                ("Year", models.IntegerField(null=True)),
                ("Make", models.CharField(max_length=255, null=True)),
                ("Model", models.CharField(max_length=255, null=True)),
                ("Category", models.CharField(max_length=255, null=True)),
                ("Class", models.CharField(max_length=255, null=True)),
                ("GearType", models.CharField(max_length=255, null=True)),
                ("EngineType", models.CharField(max_length=255, null=True)),
                ("Complex", models.BooleanField(null=True)),
                ("HighPerformance", models.BooleanField(null=True)),
                ("Pressurized", models.BooleanField(null=True)),
                ("TAA", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(null=True)),
                ("AircraftID", models.CharField(max_length=255, null=True)),
                ("From", models.CharField(max_length=255, null=True)),
                ("To", models.CharField(max_length=255, null=True)),
                ("Route", models.CharField(max_length=255, null=True)),
                ("TimeOut", models.TimeField(null=True)),
                ("TimeOff", models.TimeField(null=True)),
                ("TimeOn", models.TimeField(null=True)),
                ("TimeIn", models.TimeField(null=True)),
                ("OnDuty", models.TimeField(null=True)),
                ("OffDuty", models.TimeField(null=True)),
                (
                    "TotalTime",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("PIC", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("SIC", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "Night",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "Solo",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "CrossCountry",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("NVG", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("NVGOps", models.IntegerField(null=True)),
                (
                    "Distance",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("DayTakeoffs", models.IntegerField(null=True)),
                ("DayLandingsFullStop", models.IntegerField(null=True)),
                ("NightTakeoffs", models.IntegerField(null=True)),
                ("NightLandingsFullStop", models.IntegerField(null=True)),
                ("AllLandings", models.IntegerField(null=True)),
                (
                    "ActualInstrument",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "SimulatedInstrument",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "HobbsStart",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "HobbsEnd",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "TachStart",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "TachEnd",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("Holds", models.IntegerField(null=True)),
                ("Approach1", models.TextField(null=True)),
                ("Approach2", models.TextField(null=True)),
                ("Approach3", models.TextField(null=True)),
                ("Approach4", models.TextField(null=True)),
                ("Approach5", models.TextField(null=True)),
                ("Approach6", models.TextField(null=True)),
                (
                    "DualGiven",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "DualReceived",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "SimulatedFlight",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "GroundTraining",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("InstructorName", models.CharField(max_length=255, null=True)),
                ("InstructorComments", models.TextField(null=True)),
                ("Person1", models.TextField(null=True)),
                ("Person2", models.TextField(null=True)),
                ("Person3", models.TextField(null=True)),
                ("Person4", models.TextField(null=True)),
                ("Person5", models.TextField(null=True)),
                ("Person6", models.TextField(null=True)),
                ("FlightReview", models.BooleanField(null=True)),
                ("Checkride", models.BooleanField(null=True)),
                ("IPC", models.BooleanField(null=True)),
                ("NVGProficiency", models.BooleanField(null=True)),
                ("FAA6158", models.BooleanField(null=True)),
                ("CustomFieldNameText", models.TextField(null=True)),
                (
                    "CustomFieldNameNumeric",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("CustomFieldNameHours", models.TimeField(null=True)),
                ("CustomFieldNameCounter", models.IntegerField(null=True)),
                ("CustomFieldNameDate", models.DateField(null=True)),
                ("CustomFieldNameDateTime", models.DateTimeField(null=True)),
                ("CustomFieldNameToggle", models.BooleanField(null=True)),
                ("PilotComments", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MapperConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("config", models.JSONField()),
            ],
        ),
    ]
